name: adminpanel
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.6
  intl: ^0.19.0
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.6
  firebase_storage: ^11.6.0

  file_picker: ^5.5.0
  open_file: ^3.3.2
  image_picker: ^1.0.4
  uuid: ^4.2.2
  dio: ^5.3.3
  # syncfusion_flutter_pdfviewer: ^24.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
